name: ThePit
version: ${project.version}
authors:
  - Maximouz
  - Eclixal
main: fr.maximouz.thepit.ThePit
depend:
  - EuraCore
commands:
  area:
    aliases:
      - areas
  spawnpoint:
    aliases:
      - spawnpoints
      - sp
      - sps